# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.framescalibration_label = QtWidgets.QLabel(self.tab)
        self.framescalibration_label.setObjectName("framescalibration_label")
        self.horizontalLayout_3.addWidget(self.framescalibration_label)
        self.framescalibration_spin = QtWidgets.QSpinBox(self.tab)
        self.framescalibration_spin.setMinimum(1)
        self.framescalibration_spin.setProperty("value", 3)
        self.framescalibration_spin.setObjectName("framescalibration_spin")
        self.horizontalLayout_3.addWidget(self.framescalibration_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.blackbodytemperator_label = QtWidgets.QLabel(self.tab)
        self.blackbodytemperator_label.setObjectName("blackbodytemperator_label")
        self.horizontalLayout_4.addWidget(self.blackbodytemperator_label)
        self.blackbodytemperator_spin = QtWidgets.QDoubleSpinBox(self.tab)
        self.blackbodytemperator_spin.setSingleStep(0.1)
        self.blackbodytemperator_spin.setProperty("value", 35.0)
        self.blackbodytemperator_spin.setObjectName("blackbodytemperator_spin")
        self.horizontalLayout_4.addWidget(self.blackbodytemperator_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.calibrationcalibration_button = QtWidgets.QPushButton(self.tab)
        self.calibrationcalibration_button.setObjectName("calibrationcalibration_button")
        self.verticalLayout_2.addWidget(self.calibrationcalibration_button)
        self.importcalibration_button = QtWidgets.QPushButton(self.tab)
        self.importcalibration_button.setObjectName("importcalibration_button")
        self.verticalLayout_2.addWidget(self.importcalibration_button)
        self.matplotlib_widget = QtWidgets.QWidget(self.tab)
        self.matplotlib_widget.setObjectName("matplotlib_widget")
        self.verticalLayout_2.addWidget(self.matplotlib_widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.framestest_label = QtWidgets.QLabel(self.tab_2)
        self.framestest_label.setObjectName("framestest_label")
        self.horizontalLayout_2.addWidget(self.framestest_label)
        self.framestest_spin = QtWidgets.QSpinBox(self.tab_2)
        self.framestest_spin.setMinimum(1)
        self.framestest_spin.setProperty("value", 3)
        self.framestest_spin.setObjectName("framestest_spin")
        self.horizontalLayout_2.addWidget(self.framestest_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.testtest_button = QtWidgets.QPushButton(self.tab_2)
        self.testtest_button.setObjectName("testtest_button")
        self.verticalLayout.addWidget(self.testtest_button)
        self.matplotlib_widget_2 = QtWidgets.QWidget(self.tab_2)
        self.matplotlib_widget_2.setObjectName("matplotlib_widget_2")
        self.verticalLayout.addWidget(self.matplotlib_widget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.framescalibration_label.setText(_translate("MainWindow", "Frames:"))
        self.blackbodytemperator_label.setText(_translate("MainWindow", "First Black Body Temperature"))
        self.calibrationcalibration_button.setText(_translate("MainWindow", "Take Picture"))
        self.importcalibration_button.setText(_translate("MainWindow", "import first picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calibration"))
        self.framestest_label.setText(_translate("MainWindow", "Frames:"))
        self.testtest_button.setText(_translate("MainWindow", "Take Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Test"))

